FROM ethereum/client-go:v1.13.0

RUN apk add --no-cache jq curl

COPY entrypoint-l1.sh /entrypoint.sh

VOLUME ["/db"]

HEALTHCHECK --start-period=300s --start-interval=1s CMD curl --fail http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}'

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
