name: Docker Images

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-l1:
    uses: ./.github/workflows/docker.yml
    with:
        images: ghcr.io/espressosystems/geth-l1
        context: ./
        dockerfile: ./Dockerfile.l1
    secrets: inherit

  docker-staging-l1:
    uses: ./.github/workflows/docker.yml
    needs: docker-l1
    with:
        images: ghcr.io/espressosystems/geth-l1-staging
        context: ./
        dockerfile: ./staging.Dockerfile.l1
    secrets: inherit
