name: Docker Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docker-l1:
    uses: ./.github/workflows/docker.yml
    with:
        images: ghcr.io/espressosystems/geth-l1
        context: ./
        dockerfile: ./Dockerfile.l1
    secrets: inherit